In [2]:
import numpy as np
import time

In [3]:
#array properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #dimension=m*n
print(arr.size) #total element=9
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [4]:
#operations on np arrays
#reshaping
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened=arr.flatten()# 2D -> 1D
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [5]:
#indexing
arr1=np.array([1,2,3,4])
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0][1])
print(arr[1][0])


2
4


In [6]:
#fancy indexing
arr=np.array([1,2,3,4])

idx=[0,1,3]
print(arr[idx])

[1 2 4]


In [7]:
#boolean indexing
arr=np.array([1,2,3,4])
print(arr[arr>2])
print(arr[arr%2==0])


[3 4]
[2 4]


In [8]:
#slicing
arr=np.array([1,2,3,4,5])
print(arr[0:3])

[1 2 3]


In [9]:
#copy vs view 
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [10]:
#data type
arr=np.array([1,2,3,4])
print(arr,arr.dtype)
arr1=np.array([3+5j])
arr2=np.array([2+5j])
print(arr1-arr2,arr1.dtype)

arr3=np.array(["prime",{1,2,3},5.67,9])
print(arr3.dtype)


[1 2 3 4] int64
[1.+0.j] complex128
object
