In [1]:
import numpy as np
import time

In [2]:
#create-np array(1D) from list
arr=np.array([1,4,6,7])
print(arr,type(arr),arr.dtype,arr.shape)

arr2=np.array([1,4,6,7,"python"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)
#U21=unicode format

#create 2D array from list
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[1 4 6 7] <class 'numpy.ndarray'> int64 (4,)
['1' '4' '6' '7' 'python'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
#create array from scratch
arr1=np.zeros((2,3),dtype="int64") #prefill
print(arr1,arr1.shape)

arr2=np.ones((5,),dtype="int64") #prefill
print(arr2,arr2.shape)

arr3=np.full((3,4),100,dtype="int64") #prefill with particular value
print(arr3,arr3.shape)


arr4=np.eye((3),dtype="int64") #identity matrix
print(arr4,arr4.shape)


arr5=np.arange(1, 11, 2) #range elements
print(arr5,arr5.shape)


arr6=np.linspace(1, 100, 4) #evenly spaced array
print(arr6,arr6.shape)



[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [4]:
#execution performance
size=100_000_000
#time for python list
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python list time:{end-start} seconds")

#time for numpy arrays
np_array=np.array(py_list)
start=time.time()
sq_array=np_array ** 2
end=time.time()
print(f"numpy array time:{end-start} seconds")

python list time:26.950390815734863 seconds
numpy array time:1.064962387084961 seconds


In [2]:
#memory comparison
import sys
size=100_000_000
#time for python list
py_list=list(range(size))
np_array=np.array(py_list)
print(f"python list size: {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"python array size: {sys.getsizeof(np_array) * len(np_array)} bytes")

python list size: 80000005600000000 bytes
python array size: 80000011200000000 bytes
